# GitBook configuration for Soulbound Saga documentation
root: ./dungeon-delvers-whitepaper/gitbook-zh/

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  - from: /
    to: /README.md
  - from: /index
    to: /README.md
  - from: /home
    to: /README.md