version: '3.8'

services:
  # 簡化的 Metadata 服務
  metadata-server:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - THE_GRAPH_API_URL=https://api.studio.thegraph.com/query/115633/dungeon-delvers/version/1.2.3
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s