version: '3.8'

services:
  # 簡化的 Metadata 服務
  metadata-server:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3001
      - THE_GRAPH_API_URL=${THE_GRAPH_API_URL}
      - VITE_MAINNET_HERO_ADDRESS=${VITE_MAINNET_HERO_ADDRESS}
      - VITE_MAINNET_RELIC_ADDRESS=${VITE_MAINNET_RELIC_ADDRESS}
      - VITE_MAINNET_PARTY_ADDRESS=${VITE_MAINNET_PARTY_ADDRESS}
      - VITE_MAINNET_VIPSTAKING_ADDRESS=${VITE_MAINNET_VIPSTAKING_ADDRESS}
      - VITE_MAINNET_PLAYERPROFILE_ADDRESS=${VITE_MAINNET_PLAYERPROFILE_ADDRESS}
      - FRONTEND_DOMAIN=${FRONTEND_DOMAIN:-https://dungeondelvers.xyz}
      - TEST_MODE=${TEST_MODE:-false}
    volumes:
      - ../api:/app/api:ro
      - ../public:/app/public:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s